spring:
  application:
    name: task-management-api
  
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanagement
    username: ${DB_USERNAME:taskuser}
    password: ${DB_PASSWORD:taskpass}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  cache:
    type: simple

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
    expiration: 86400000 # 24 hours
    refresh-expiration: 604800000 # 7 days
  
  admin:
    email: ${ADMIN_EMAIL:admin@taskmanagement.com}
    password: ${ADMIN_PASSWORD:Admin123!}

logging:
  level:
    com.nazar.taskmanagement: DEBUG
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
